// frontend/src/app/components/login/login.component.ts
import { Component } from "@angular/core";
import * as $ from "jquery";


@Component({
    selector: 'app-layout-login',
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.css']
})


export class Login {
    constructor() {
        console.log('==con==');

    }

    ngOnInit() {

    }

    onClickNextBtn() {
        console.log('==click==');
        setTimeout(() => {
            console.log('==2 sec==');
            $('#inputEmail').hide()
            $('#inputFieldsParentDiv').append('<input type="password" class="form-control" id="inputEmail" placeholder="Please Enter Password" style="border: 3px solid 474e5d;">')
        }, 2000)
    }



}
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100">

        <div class="col-4 hidden-md-down" id="yellow">
            <div class="div" style="padding-top: 50%;">
                <div>
                    <p style="font-size: 40px;">Login Here</p>
                </div>
                <div class="form-group" id="inputFieldsParentDiv">
                    <input type="text" class="form-control" id="inputEmail" placeholder="Email"
                        style="border: 3px solid 474e5d;">
                </div>

                <button type="submit" class="btn btn-primary mb-2" style="height: 35px;width: 100px;margin-top:10px"
                    id="NextBtnID" (click)="onClickNextBtn()">Next</button>
            </div>
            <div>
                <br />
                <p style="font-size: 10px;font-family:Arial, Helvetica, sans-serif;"> <a href="#">Reset Password</a></p>
            </div>
        </div>

        <div class="col-10 col-sm-10 col-md-10 col-lg-8 col-xl-8" id="black">

            <div class="container" style="padding-top: 160px;">
                <div class="screen monitor">
                    <div class="content">
                        <div class="pg">
                            <ul class="btns">
                                <li></li>
                                <li></li>
                                <li></li>
                            </ul>
                            <ul class="txt">
                                <li></li>
                                <li></li>
                                <li class="thin"></li>
                                <li class="thin"></li>
                                <li class="thin"></li>
                            </ul>
                        </div>
                    </div>
                    <div class="base">
                        <div class="grey-shadow"></div>
                        <div class="foot top"></div>
                        <div class="foot bottom"></div>
                        <div class="shadow"></div>
                        <div class="keyboard">
                            <div class="btm"></div>
                            <ul class="keys">
                                <li></li>
                                <li></li>
                                <li></li>
                                <li></li>
                            </ul>
                            <div class="shadow"></div>
                        </div>
                    </div>
                </div>
                <div class="laptop">
                    <div class="content">
                        <ul class="txt txt-laptop">
                            <li></li>
                            <li></li>
                            <li class="thin"></li>
                            <li class="thin"></li>
                            <li class="thin"></li>
                        </ul>
                    </div>
                    <div class="btm"></div>
                    <div class="shadow"></div>
                </div>
                <div class="phone">
                    <div class="screen">
                        <div class="content">
                            <ul class="txt">
                                <li></li>
                                <li></li>
                                <li></li>
                            </ul>
                        </div>
                    </div>

                    <div class="shadow"></div>
                </div>

            </div>

        </div>
    </div>
</div>


















<!-- <div class="" id="grad1">
    <div class="row justify-content-center mt-0">
        <div class="col-11 col-sm-9 col-md-7 col-lg-6 text-center p-0 mt-3 mb-2">
            <div class="card px-0 pt-4 pb-0 mt-3 mb-3">
                <h2><strong>Log in to Portal</strong></h2>
                <p>Are you new? <a href="/signup">Sign up Here</a></p>
                <div class="row">
                    <div class="col-md-12 mx-0">
                        <form id="msform">
                            <fieldset>
                                <div class="form-card">
                                    <h2 class="fs-title">Login</h2>
                                    <br />
                                    <input type="email" name="email" placeholder="Email Id" />
                                    <input type="password" name="pwd" placeholder="Password" />

                                    <div class='row'>
                                        <div class="col-md-4 mx-0">
                                        </div>

                                        <div class="col-md-5 mx-0">
                                            <button class="btn btn-lg btn-primary"
                                                style="height: 35px;width: 100px;">Login</button>

                                        </div>
                                        <div class="col-md-3 mx-0">
                                            <p><a href="/home" style="float: right;font-size: 9px;">Reset Password
                                                </a></p>
                                        </div>
                                    </div>
                                </div>


                            </fieldset>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->

// client/src/component/Login.jsx
import React, { Component } from 'react'
import '../style/Signup.css';

export default class Login extends Component {


    render() {
        return (
            <>
                <div className="container-fluid" id="grad1">
                    <div className="row justify-content-center mt-0">
                        <div className="col-11 col-sm-9 col-md-7 col-lg-6 text-center p-0 mt-3 mb-2">
                            <div className="card px-0 pt-4 pb-0 mt-3 mb-3">
                                <h2><strong>Log in to Portal</strong></h2>
                                <p>Are you new? <a href="/signup">Sign up Here</a></p>
                                <div className="row">
                                    <div className="col-md-12 mx-0">
                                        <form id="msform">
                                            {/* <ul id="progressbar">
                                                <li className="active" id="account"><strong>Account</strong></li>
                                            </ul> */}
                                            <fieldset>
                                                <div className="form-card">
                                                    <h2 className="fs-title">Login</h2>
                                                    < br />
                                                    <input type="email" name="email" placeholder="Email Id" />
                                                    <input type="password" name="pwd" placeholder="Password" />

                                                </div>

                                                <br />
                                                <div className='row'>
                                                    <div className="col-md-4 mx-0">
                                                        <p>Forgot Password? <a href="#">Click Here</a></p>
                                                    </div>

                                                    <div className="col-md-4 mx-0">
                                                    </div>
                                                    <div className="col-md-4 mx-0">
                                                        <p>Need Help? <a href="/home">Click Here</a></p>
                                                    </div>
                                                </div>
                                                {/* <p>Forgot Password? <a href="#">Click Here</a></p> */}
                                                <input type="button" name="next" className="next action-button" value="Log in" style={{ background: 'darkcyan' }} />
                                            </fieldset>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        )
    }
}
